name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # self-hosted 러너를 사용

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t kydocker066/your-app-name:latest .

    - name: Push Docker image to Docker Hub
      run: docker push kydocker066/your-app-name:latest

    - name: Set kubectl context
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_CONTENTS }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/your-deployment-name your-container-name=kydocker066/your-app-name:latest
        kubectl rollout status deployment/your-deployment-name
